import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-black p-3">
          <h1 className="text-white text-xl font-bold">Code Snippet</h1>
        </div>
        <div className="mx-auto container px-12 mt-5">
        {children}

        </div>
      </body>
    </html>
  );
}
